### ISSUE TITLE
Works on one display, but not on another

### ISSUE THREAD

**Issue by CrazyCoder** [CoenraadS/Steam-Maximize-Fix#5]
I have 3 display setup and just tried 2.1 version.

Displays are as follows:

left: 1200x1920 (portrait)
center: 2560x1600 (landscape)
right: 1200x1920 (portrait)

![display layout](https://dl.dropboxusercontent.com/u/2752840/ShareXmod/2015-01/Monitor_Configuration_%E2%80%A2_DisplayFusion_Pro_on_Steam_2015-01-28_17-52-19.png)

As expected, it maximizes fine on the main center display.
It also maximizes correctly on the left display after I start this tool.
However, it doesn't work for the right display, the window is maximized incorrectly, just like if the fix was not running at all.

Not sure if it matters, but I'm using DisplayFusion on 64-bit Windows 7 system. My left and right displays have taskbar on top. The center display has taskbar on the left side.

**Comment by CoenraadS** [comment]
Unfortunately I only have two monitors, so this is hard for me to test.

However if I set my left as primary with taskbar on the left, and the right with taskbar on the top, I do get Steam maximizing too small. In my previous testing Steam only maximized incorrectly on the left monitors so I only programmed left checks. I'll look into this, thanks for reporting.

**Comment by CoenraadS** [comment]
When it maximizes incorrectly on the right screen, could you describe its behavior? Is the window still visible at all? Is it too large/small?

**Comment by CrazyCoder** [comment]
It has the size of the main display (2560x1600) and is aligned to the top left corner of the screen, without considering that I have a taskbar on top, so it's under the taskbar:

![right display maximize issue](https://dl.dropboxusercontent.com/u/2752840/ShareXmod/2015-01/2015-01-28_18-19-32.png)

**Comment by CoenraadS** [comment]
Could you try v2.2 out?

https://github.com/CoenraadS/Steam-Maximize-Fix/releases/tag/v2.2

**Comment by CrazyCoder** [comment]
2.2 works fine! Thanks for the instant fix.
